config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resources :tools

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  root to: "welcome#show"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tools
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :name, presence: true
  validates :user, presence: true
  validates :category, presence: true

  belongs_to :user
  belongs_to :category

  def formatted_price
    price / 100.0
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  has_secure_password
  has_many :tools
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :most_recent_tool
  helper_method :current_tool_summary
  helper_method :current_user
  helper_method :logged_in?

  def most_recent_tool
    @most_recent_tool ||= Tool.find(session[:most_recent_tool_id]) if session[:most_recent_tool_id]
  end

  def current_tool_summary
    "Current tool count: #{session[:current_tool_count].to_i}
     Current potential revenue: $#{sprintf('%.2f',session[:current_potential_revenue].to_f)}"
  end

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(session[:user_id])
    else
      flash.now[:error] = "Incorrect login credentials"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tools = current_user.tools
  end

  def show
    @tool = Tool.find(params[:id])
    render file: "/public/404" unless current_user == @tool.user
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    if @tool.save
      session[:current_tool_count] = session[:current_tool_count].to_i + @tool.quantity
      session[:current_potential_revenue] = session[:current_potential_revenue].to_f + @tool.quantity*@tool.formatted_price
      session[:most_recent_tool_id] = @tool.id
      flash[:notice] = "Tool successfully created"
      redirect_to @tool
    else
      flash.now[:error] = @tool.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @tool = Tool.find(params[:id])
    @user = current_user
  end

  def update
    @tool = Tool.find(params[:id])
    @tool.update(tool_params)
    if @tool.save
      redirect_to tool_path(@tool.id)
    else
      render :edit
    end
  end

  def destroy
    Tool.destroy(params[:id])
    redirect_to tools_path
  end



  private

  def tool_params
    params.require(:tool).permit(:name, :price, :quantity, :category_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:notice] = "Did not create account, please try again"
      render :new
    end
  end

  def show
    @user = current_user
  end

private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    if logged_in?
      redirect_to user_path(current_user)
    else
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container">
    <% if logged_in? %>
    <h2><%= link_to "Logout", logout_path, method: "delete"%></h2>

    <p><strong>Newest tool:</strong> <%= "#{most_recent_tool.name}" if most_recent_tool %></p>
    <p><strong>Current Sessions Tool Summary:</strong></p>
    <p><%= current_tool_summary %></p>
    <% end %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/tools/_form.html.erb
<%= form_for @tool do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.submit %>
<% end %>

app/views/tools/edit.html.erb
<%= render "form" %>

app/views/tools/index.html.erb
<h1><%=current_user.username %>'s Tools</h1>

<div class="tools">
  <% @tools.each do |tool| %>
    <h3><%= link_to "#{tool.name}", user_tool_path(tool) %><%="- #{tool.quantity}"%></h3>
  <% end %>
</div>
<button type="button"><%= link_to "Create new tool", new_user_tool_path %></button>

app/views/tools/new.html.erb
<%= render "form" %>

app/views/tools/show.html.erb
<div class = "tool_info">
<h1><%= "#{@tool.name} - #{@tool.quantity}" %></h1>
<h3><%= "Price: $#{sprintf('%.2f', @tool.formatted_price)}" %></h3>
</div>
<%= link_to "Edit #{@tool.name}", edit_tool_path(@tool) %>
<%= link_to "Back to #{current_user.username}'s tools", user_path(current_user) %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Create Account"%>
<% end %>

app/views/users/show.html.erb
<%= "#{current_user.username}'s tools:" %>
<ul id= "tools">
  <% current_user.tools.each do |tool| %>
    <li><%= link_to tool.name, tool_path(tool) %></li>
  <% end %>
</ul>
<%= link_to "Create New Tool", new_tool_path %>

app/views/welcome/show.html.erb
<h2><%= link_to "Create new account", new_user_path %></h2>
<h2><%= link_to "Login to existing account", login_path %></h2>